import Head from 'next/head';
import React, { ReactElement } from 'react';
import { Layout } from '../components/layout/Layout';
import { NextPageWithLayout } from '../types/global';

const Home: NextPageWithLayout = () => (
  <>
    <Head>
      <title>Uwazi</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className="text-3xl font-bold underline">Hello uwazi!</h1>
  </>
);

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
