import Head from 'next/head';
import React from 'react';
import { NextPageWithLayout } from '../types/global';

const Home: NextPageWithLayout = () => (
  <>
    <Head>
      <title>Uwazi</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className="text-3xl font-bold underline">Hello uwazi!</h1>
  </>
);

export default Home;
