name: Modules security check

on:
  push:
    branches:
      - production
      - development
      - staging
  pull_request:

jobs:
  yarn-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn audit --level high --groups dependencies || if [ $? -gt 8 ]; then exit 1; else exit 0; fi
